apiVersion: v1
kind: Service
metadata:
  name:  nihal-rtp-service
  namespace: nihal
spec:
  type: NodePort
  selector:
    app: nihal-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
