sonar.verbose=true
sonar.organization=nihal-org
sonar.projectKey=nihal-org_nihal-project
sonar.projectName=nihal-project
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
